// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoSoItAbIa_EgGLOQcQXTJkuLVzy3-3vk',
    appId: '1:177386126258:web:22a281fae18a11d04c82ab',
    messagingSenderId: '177386126258',
    projectId: 'raifurogu-ad46a',
    authDomain: 'raifurogu-ad46a.firebaseapp.com',
    storageBucket: 'raifurogu-ad46a.appspot.com',
    measurementId: 'G-MVYWG6K4W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUgZreHCpIi_FQ4ZuWFRwvM6g7HkvQR0A',
    appId: '1:177386126258:android:b0aae6d9b247c2504c82ab',
    messagingSenderId: '177386126258',
    projectId: 'raifurogu-ad46a',
    storageBucket: 'raifurogu-ad46a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Oql-r3G3Zvx1bvSsbuNBF18TspANTEk',
    appId: '1:177386126258:ios:8305b5704c0849c24c82ab',
    messagingSenderId: '177386126258',
    projectId: 'raifurogu-ad46a',
    storageBucket: 'raifurogu-ad46a.appspot.com',
    iosClientId: '177386126258-ni9n3krdr31ri4gpemc0ovtclvbt89up.apps.googleusercontent.com',
    iosBundleId: 'com.example.raifurogu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Oql-r3G3Zvx1bvSsbuNBF18TspANTEk',
    appId: '1:177386126258:ios:8305b5704c0849c24c82ab',
    messagingSenderId: '177386126258',
    projectId: 'raifurogu-ad46a',
    storageBucket: 'raifurogu-ad46a.appspot.com',
    iosClientId: '177386126258-ni9n3krdr31ri4gpemc0ovtclvbt89up.apps.googleusercontent.com',
    iosBundleId: 'com.example.raifurogu',
  );
}
